### ISSUE TITLE
'Response' object has no attribute 'cookiejar'

### ISSUE THREAD

**Issue by oriolval** [lanmaster53/recon-ng-marketplace#105] opened 2020-03-29 09:18 UTC
**Module Name**
Netcraft
**Bug Description**
When I try to run recon-ng with the module netcraft, the execution fails showing the error _'Response' object has no attribute 'cookiejar'_

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Go to recon-ng in your Kali Linux
2. Install the module recon/domain-hosts/netcraft
3. Load the netcraft module
4. Set any source
5. Make run
6. See the error I paste above

**Expected Behavior**
This module should print all the subdomains of the source we have selected, but shows the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/32534815/77845405-02e50380-71af-11ea-8f59-66bb974c5cab.png)

**Comment by khalil2535** [comment] 2020-04-05 03:52
Same here

**Comment by lanmaster53** [comment] 2020-04-07 01:41
Duplicate of #30.

**Closed by lanmaster53** 2020-04-07 01:41 UTC
Labels: bug
