### ISSUE TITLE
netcraft not working

### ISSUE THREAD

**Issue by mehrabix** [lanmaster53/recon-ng-marketplace#60] opened 2019-09-03 12:01 UTC
when i run netcraft i get this error:
![image](https://user-images.githubusercontent.com/30565212/64171550-399caa80-ce68-11e9-8471-42ceafd4fe9b.png)

**Comment by lanmaster53** [comment] 2019-09-11 01:02
Duplicate of #30.

**Closed** 2019-09-11 01:04 UTC
