### ISSUE TITLE
Error message using recon/netblocks-companies/whois_orgs module 

### ISSUE THREAD

**Issue by yonaszeru** [lanmaster53/recon-ng-marketplace#208] opened 2021-07-21 10:02 UTC
**To save some time, have you:**
- [x] Checked the [wiki](https://github.com/lanmaster53/recon-ng/wiki) 
- [x] Checked previously answered [questions](https://github.com/lanmaster53/recon-ng-marketplace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3Aquestion)

**Please ask the question below**  
\[Please be as detailed as possible.\]

**Comment by yonaszeru** [comment] 2021-07-21 10:10
Everytime I use recon/netblocks-companies/whois_orgs module I get an error message. I tried but I am not familiar with python . Below is  copy of the Error message 

Traceback (most recent call last):                                                                                                                                         
  File "/home/kali/recon-ng/recon/core/module.py", line 347, in do_run                                                                                                     
    self.run()                                                                                                                                                             
  File "/home/kali/recon-ng/recon/core/module.py", line 341, in run                                                                                                        
    self.module_run(*params)                                                                                                                                               
  File "/home/kali/.recon-ng/modules/recon/netblocks-companies/whois_orgs.py", line 25, in module_run                                                                      
    if ref in resp.json()['net']:                                                                                                                                          
  File "/home/kali/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json                                                                               
    return complexjson.loads(self.text, **kwargs)                                                                                                                          
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads                                                                                         
    return _default_decoder.decode(s)                                                                                                                                      
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode                                                                                         
    obj, end = self.raw_decode(s)                                                                                                                                          
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode                                                                                     
    return self.scan_once(s, idx=_w(s, idx).end())                                                                                                                         
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                               
------------------------------------------------------------                                                                                                               
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by lanmaster53** [comment] 2021-08-25 04:31
Duplicate of #209

**Closed by lanmaster53** 2021-08-25 04:31 UTC
Labels: question
