### ISSUE TITLE
something is broken

### ISSUE THREAD

**Issue by TomaszMyszak** [lanmaster53/recon-ng-marketplace#212] opened 2021-08-03 04:56 UTC
when I use recon/contacts-credentials/hibp_breach

I have a answer:

[!] String indices must be integers.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

enybody help?

**Comment by lanmaster53** [comment] 2021-08-25 03:00
Duplicate of #191

**Closed** 2021-08-25 03:00 UTC
